# Application
spring.application.name=fullstack-crud-book
server.port=8088

# JWT Configuration
jwt.secret=9a4f2c8d3b7a1e6f5c9a8b7f4e5d3c2b1a6f5e4d3c2b1a9f8e7d6c5b4a3f2e1d0
jwt.expiration=86400000

# MariaDB Configuration
spring.datasource.url=jdbc:mariadb://localhost:3306/CrudBookDB?createDatabaseIfNotExist=true
spring.datasource.username=userBook
spring.datasource.password=userBook
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDB106Dialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Initialisation des données
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true