spring.application.name=fullstack-crud-book
# JWT Configuration
jwt.secret=9a4f2c8d3b7a1e6f5c9a8b7f4e5d3c2b1a6f5e4d3c2b1a9f8e7d6c5b4a3f2e1d0
# Durée de validité du token (24h en ms)
jwt.expiration=86400000  
# H2 Configuration
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=cmc
spring.datasource.password=cmc

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=true
spring.h2.console.settings.web-allow-others=true

# JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Initialisation des données - CORRECTION ICI
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true
server.port=8088